# Generated by Django 4.1.7 on 2023-03-10 12:00

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_contactinformation_socialaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=120)),
                ('icon', models.ImageField(upload_to='service')),
                ('short_description', models.TextField()),
                ('details', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'verbose_name_plural': 'Service',
            },
        ),
        migrations.AlterModelOptions(
            name='socialaccount',
            options={'verbose_name': 'Social Account', 'verbose_name_plural': 'Social Accounts'},
        ),
    ]
